// Package docs provides API documentation generated by Swagger
package docs

import "github.com/swaggo/swag"

// @title          Platform API
// @version        1.0
// @description    Go-based backend platform service featuring user, organization, and role management
// @termsOfService http://swagger.io/terms/

// @contact.name  OneDotNet Team
// @contact.url   https://onedotnet.org
// @contact.email support@onedotnet.org

// @license.name Apache 2.0
// @license.url  http://www.apache.org/licenses/LICENSE-2.0.html

// @host     localhost:8080
// @BasePath /api/v1

// @securityDefinitions.apikey BearerAuth
// @in header
// @name Authorization
// @description Enter the token with the `Bearer: ` prefix, e.g. "Bearer abcde12345".

// @tag.name Users
// @tag.description User management endpoints

// @tag.name Organizations
// @tag.description Organization management endpoints

// @tag.name Roles
// @tag.description Role management endpoints

// @tag.name Authentication
// @tag.description Authentication and authorization endpoints

// GetSwaggerSpec returns the Swagger specification
func GetSwaggerSpec() *swag.Spec {
	return SwaggerInfo
}
